// <auto-generated />
namespace Slacker.ApplicationMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SpentGainedStatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SpentGainedStatus));
        
        string IMigrationMetadata.Id
        {
            get { return "201803051600055_SpentGainedStatus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
